[package]
name = "smawk"
version = "0.3.2"
authors = ["Martin Geisler <martin@geisler.net>"]
categories = ["algorithms", "mathematics", "science"]
edition = "2021"
exclude = [".github/", ".gitignore", "benches/", "examples/"]
keywords = ["smawk", "matrix", "optimization", "dynamic-programming"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/mgeisler/smawk"
description = "Functions for finding row-minima in a totally monotone matrix."

[dependencies]
num-traits = { version = "0.2.14", optional = true }
ndarray = { version = "0.17.1", optional = true }

[dev-dependencies]
rand = "0.9.2"
version-sync = "0.9.4"
