version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Pull xd009642/tarpaulin
          command: docker pull xd009642/tarpaulin
      - run:
          name: Generate coverage report
          command: >-
            docker run --security-opt seccomp=unconfined
            -v $PWD:/volume xd009642/tarpaulin
            cargo tarpaulin --out Xml
      - run:
          name: Upload to codecov.io
          command: bash <(curl -s https://codecov.io/bash) -Z -f cobertura.xml
