name: build

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        rust:
          - stable
          - nightly

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install ${{ matrix.rust }} Rust
        run: rustup default ${{ matrix.rust }}

      # Quick smoke test to detect serious brokenness.
      - name: Build with default features
        run: cargo build

      - name: Build with all features
        run: cargo build --all-features

      # Restrict to nightly since benchmarks only work there.
      - name: Build all targets with all features
        if: matrix.rust == 'nightly'
        run: cargo build --all-targets --all-features

      - name: Run tests with all features
        run: cargo test --all-features
